### ISSUE TITLE
cant type password

### ISSUE THREAD

**Issue by XVR1212** [rousez/Auto-Amazon-Giveaways#2]
![bvpo_4l3srs6aevfexfhkw](https://user-images.githubusercontent.com/30773996/30217177-0a3bb1e0-94be-11e7-8c16-7c0049b54cca.png)
for some reason i cant type password

**Comment by zdrouse** [comment]
You should be able to - the getpass module in Python takes the input but does not display the password or asterisks.  It is being entered but you will not see output, very similar to remotely logging into a linux server over SSH.  Feed the script your email address and password that you use for Amazon account.

I'm still working on improving this project - keep in mind you may encounter a few issues.  Thanks.

**Comment by XVR1212** [comment]
@rousez Well so now I have another problem
![oliibw_kqrgmcilshsmf7g](https://user-images.githubusercontent.com/30773996/30224644-3b0615da-94d8-11e7-93a5-6da23144920e.png)
It opens the google chrome giveaway page, But it does not do anything after that

**Comment by zdrouse** [comment]
I see.  Amazon appears to have changed their mobile view since I last updated this.  In the chromedriver options I was sending the mobile user agent.  I have fixed this and pushed to the repo.  Please try doing a full git clone or git pull on your machine.  Should be fixed now.  (You'll also need to edit the line where your chromedriver path is specified, but I think you already know that)

Another thing, if you have not already linked a Twitter account with your Amazon account then the first Twitter giveaway will ask you to do that.  In which case the script does not know how to handle that.  However after you link a twitter account you will not encounter that again.  I recommend using a bogus Twitter account for this.

**Comment by XVR1212** [comment]
@rousez 
I did everything you said, link my twitter account, full git clone 
This time it worked for a few moments and then the problem started again
![qzoyp8ncrlu1f1reuvdnpw](https://user-images.githubusercontent.com/30773996/30228929-82249fbc-94e8-11e7-953f-561a4f5a4951.png)
But there has been a significant improvement 👍 
(thank you for helping)

**Comment by XVR1212** [comment]
@rousez 
I checked the subject and it turns out that every time I get to the page listed, 'Do you have a US shipping address?' P.O. Boxes are not eligible '' It simply stops working
![4w1-gkkws6mtpss-vf7lwg](https://user-images.githubusercontent.com/30773996/30229238-c6ff52de-94e9-11e7-925c-1ee988c2ab2b.png)

**Comment by Wingman4l7** [comment]
@XVR1212  The script is not currently equipped to handle the scenario of the Yes/No boxes that you described.  Having a default shipping address set in your Amazon account that is not a PO box, would likely prevent this scenario from occurring.

**Comment by zdrouse** [comment]
@Wingman4l7  @XVR1212 
That's likely the case.  There is a lot that the script doesn't do yet.  I am currently completely revamping it anyhow.  It needs adhere to some better programming practices - thus it will be easier for me to maintain and improve it.

**Comment by kornj** [comment]
Is it possible that Amazon changed its mobile site again? I'm getting the same problem as XVR1212 with the Traceback
Looks [like it changed from what's currently in line 14](https://docs.aws.amazon.com/silk/latest/developerguide/user-agent.html):

**Comment by zdrouse** [comment]
@kornj It definitely has changed since I last worked on this project.  You might want to give @Tannz0rz fork a whirl - a lot of code changes are there that I would have liked to improve myself.

https://github.com/Tannz0rz/Auto-Amazon-Giveaways

**Comment by kornj** [comment]
@zdrouse Thanks, Running into the same problem over there, but I appreciate the pointer
